// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/create-game": {
    params: {};
  };
  "/join-game": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/create-game" | "/join-game";
  };
  "routes/menu.tsx": {
    id: "routes/menu";
    page: "/";
  };
  "routes/createGame.tsx": {
    id: "routes/createGame";
    page: "/create-game";
  };
  "routes/joinGame.tsx": {
    id: "routes/joinGame";
    page: "/join-game";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/menu": typeof import("./app/routes/menu.tsx");
  "routes/createGame": typeof import("./app/routes/createGame.tsx");
  "routes/joinGame": typeof import("./app/routes/joinGame.tsx");
};